import 'package:car_rental/car_model_class/car.dart';

class CarList {
  List<Car> carList = [
    Car(
      id: "1", // Converted to String
      carName: "Toyota Corolla",
      datePurchased: null, // Use null for now
      amount: 3500.0,
      transmission: "Automatic",
      type: "Sedan",
      imageName: "toyota_corolla.jpg",
      speed: 180.0,
    ),
    Car(
      id: "2",
      carName: "Honda Civic",
      datePurchased: null,
      amount: 2000.0,
      transmission: "Manual",
      type: "Sedan",
      imageName: "honda_civic.jpg",
      speed: 200.0,
    ),
    Car(
      id: "3",
      carName: "Ford Mustang",
      datePurchased: null,
      amount: 10000.0,
      transmission: "Automatic",
      type: "Sportscar",
      imageName: "ford_mustang.jpg",
      speed: 250.0,
    ),
    Car(
      id: "4",
      carName: "Toyota Vios",
      datePurchased: null,
      amount: 2000.0,
      transmission: "Automatic",
      type: "Sedan",
      imageName: "toyota_vios.jpg",
      speed: 170.0,
    ),
    Car(
      id: "5",
      carName: "Lamborghini",
      datePurchased: null,
      amount: 15000.0,
      transmission: "Automatic",
      type: "Sportscar",
      imageName: "lamborghini.jpg",
      speed: 350.0,
    ),
    Car(
      id: "6",
      carName: "Range Rover",
      datePurchased: null,
      amount: 18000.0,
      transmission: "Automatic",
      type: "SUV",
      imageName: "range_rover.jpg",
      speed: 210.0,
    ),
    Car(
      id: "7",
      carName: "Tesla",
      datePurchased: null,
      amount: 20000.0,
      transmission: "Automatic",
      type: "Sedan",
      imageName: "tesla.jpg",
      speed: 250.0,
    ),
    Car(
      id: "8",
      carName: "Mitsubishi Montero",
      datePurchased: null,
      amount: 4000.0,
      transmission: "Automatic",
      type: "SUV",
      imageName: "mitsubishi_montero.jpg",
      speed: 190.0,
    ),
    Car(
      id: "9",
      carName: "Ford Ranger",
      datePurchased: null,
      amount: 7000.0,
      transmission: "Manual",
      type: "Pickup",
      imageName: "ford_ranger.png",
      speed: 180.0,
    ),
    Car(
      id: "10",
      carName: "Toyota Fortuner",
      datePurchased: null,
      amount: 6000.0,
      transmission: "Automatic",
      type: "SUV",
      imageName: "toyota_fortuner.jpg",
      speed: 200.0,
    ),
    Car(
      id: "11",
      carName: "Nissan Patrol",
      datePurchased: null,
      amount: 9000.0,
      transmission: "Manual",
      type: "SUV",
      imageName: "nissan_patrol.jpg",
      speed: 200.0,
    ),
    Car(
      id: "12",
      carName: "Toyota HiAce",
      datePurchased: null,
      amount: 12000.0,
      transmission: "Manual",
      type: "Passenger Van",
      imageName: "toyota_hiace.png",
      speed: 160.0,
    ),
    Car(
      id: "13",
      carName: "Ford Transit",
      datePurchased: null,
      amount: 13000.0,
      transmission: "Manual",
      type: "Passenger Van",
      imageName: "ford_transit.png",
      speed: 170.0,
    ),
    Car(
      id: "14",
      carName: "Nissan Urvan",
      datePurchased: null,
      amount: 10000.0,
      transmission: "Manual",
      type: "Passenger Van",
      imageName: "nissan_urvan.jpg",
      speed: 150.0,
    ),
    Car(
      id: "15",
      carName: "Hyundai Staria",
      datePurchased: null,
      amount: 15000.0,
      transmission: "Manual",
      type: "Passenger Van",
      imageName: "hyundai_staria.jpg",
      speed: 185.0,
    ),
    Car(
      id: "16",
      carName: "Ferrari 488 GTB",
      datePurchased: null,
      amount: 25000.0,
      transmission: "Manual",
      type: "Sportscar",
      imageName: "ferrari_488gtb.jpg",
      speed: 330.0,
    ),
    Car(
      id: "17",
      carName: "Porsche 911 Turbo S",
      datePurchased: null,
      amount: 25000.0,
      transmission: "Manual",
      type: "Sportscar",
      imageName: "porsche_911.jpg",
      speed: 330.0,
    ),
    Car(
      id: "18",
      carName: "Nissan GT-R",
      datePurchased: null,
      amount: 23000.0,
      transmission: "Automatic",
      type: "Sportscar",
      imageName: "nissan_gtr.jpg",
      speed: 315.0,
    ),
    Car(
      id: "19",
      carName: "Ford F-150 Raptor",
      datePurchased: null,
      amount: 25000.0,
      transmission: "Manual",
      type: "Pickup",
      imageName: "ford_f150.jpg",
      speed: 180.0,
    ),
    Car(
      id: "20",
      carName: "Toyota Hilux",
      datePurchased: null,
      amount: 25000.0,
      transmission: "Manual",
      type: "Pickup",
      imageName: "toyota_hulix.png",
      speed: 170.0,
    ),
    Car(
      id: "21",
      carName: "Chevrolet Silverado 1500",
      datePurchased: null,
      amount: 25000.0,
      transmission: "Manual",
      type: "Pickup",
      imageName: "chevrolet_silverado.png",
      speed: 180.0,
    ),
    Car(
      id: "22",
      carName: "Nissan Navara",
      datePurchased: null,
      amount: 25000.0,
      transmission: "Manual",
      type: "Pickup",
      imageName: "nissan_navara.jpg",
      speed: 175.0,
    ),
  ];
}
